import BetaNav from "@/components/landing/beta-nav";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <div className="h-max bg-black w-full relative">
        <BetaNav />
        {children}
    </div>
  );
}
